# Autoscaling settings
autoscaling:
  enabled: false

# Deployment settings
replicaCount: 1

# Image settings
image:
  repository: dclinics/linux-labs
  tag: "v1"
  pullPolicy: IfNotPresent

# Annotations and labels for the pods
podAnnotations: {}
podLabels: {}

# Image pull secrets
imagePullSecrets: []

# Security context for the pod and container
podSecurityContext: {}
securityContext: {}

# Probes for liveness and readiness
livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  timeoutSeconds: 5

# Resource requests and limits
resources: {}

# Volume mounts and volumes
volumeMounts:
  - name: questions-volume
    mountPath: /app/config

# Node selector, affinity, and tolerations
nodeSelector: {}
affinity: {}
tolerations: {}

# Ingress settings
ingress:
  enabled: false
  hosts: []
  tls: false