apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devopclinics-lab.fullname" . }}-questions
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devopclinics-lab.labels" . | nindent 4 }}
data:
  title: "{{ .Values.configData.config.title }}" 
  questions.json: |
    {{- toYaml .Values.configData.questions | default "[]" | nindent 4 }}
