apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopclinics-lab.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "devopclinics-lab.labels" . | nindent 4 }}
    app: {{ .Values.appLabels.app }}
    instance: {{ .Values.appLabels.instance }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabels.app }}
      instance: {{ .Values.appLabels.instance }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabels.app }}
        instance: {{ .Values.appLabels.instance }}
        {{- include "devopclinics-lab.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        - name: questions-volume
          configMap:
            name: {{ .Values.configData.configMapName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
